# Generated by Django 4.2.5 on 2024-12-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_category', '0002_alter_affiliation_name_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'verbose_name': 'Принадлежность', 'verbose_name_plural': 'Принадлежности'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterModelOptions(
            name='formframe',
            options={'verbose_name': 'Форма Оправы', 'verbose_name_plural': 'Формы Оправы'},
        ),
        migrations.AlterModelOptions(
            name='framesize',
            options={'verbose_name': 'Размер Рамки', 'verbose_name_plural': 'Размеры Рамок'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='sizebridgenose',
            options={'verbose_name': 'Размер Переносицы', 'verbose_name_plural': 'Размеры Переносиц'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'verbose_name': 'Конструкция', 'verbose_name_plural': 'Конструкции'},
        ),
        migrations.AlterModelOptions(
            name='templelength',
            options={'verbose_name': 'Длина Заушника', 'verbose_name_plural': 'Длины Заушников'},
        ),
    ]
