# Generated by Django 4.2.5 on 2024-12-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_test_signup', '0002_signupeyetest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupeyetest',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
