# Generated by Django 4.2.5 on 2024-12-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_test_signup', '0003_signupeyetest_telegram_message_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupeyetest',
            old_name='review',
            new_name='comment',
        ),
    ]
