# Generated by Django 4.2.5 on 2024-12-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_test_signup', '0004_rename_review_signupeyetest_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupeyetest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='signupeyetest',
            name='telegram_message_id',
        ),
    ]
