# Generated by Django 4.2.5 on 2024-12-06 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eye_test_signup', '0005_remove_signupeyetest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupeyetest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupeyetest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
