# Generated by Django 4.2.5 on 2024-12-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_info", "0002_achievement_created_at_achievement_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
